import jsPDF from "jspdf";

/**
 * Draws the Assembl logo and header branding on a jsPDF document.
 * Returns the Y position after the header.
 */
export function drawAssemblPDFHeader(
  doc: jsPDF,
  options: {
    agentName?: string;
    agentDesignation?: string;
    subtitle?: string;
    margin?: number;
  } = {}
): number {
  const { agentName, agentDesignation, subtitle, margin = 20 } = options;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 18;

  // Green accent bar at top
  doc.setFillColor(0, 255, 136);
  doc.rect(0, 0, pageWidth, 3, "F");

  // Logo mark — triangle icon
  const lx = margin;
  const ly = y + 2;
  doc.setFillColor(0, 255, 136);
  doc.triangle(lx, ly + 8, lx + 4, ly, lx + 8, ly + 8, "F");
  doc.setFillColor(0, 229, 255);
  doc.circle(lx + 4, ly - 1, 1.2, "F");

  // Brand name
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 35);
  doc.text("ASSEMBL", margin + 12, y + 7);

  // Tagline
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(130);
  doc.text("assembl.co.nz", margin + 12, y + 11);

  y += 16;

  // Agent info line
  if (agentName) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60);
    const agentLine = agentDesignation
      ? `${agentName} (${agentDesignation})`
      : agentName;
    doc.text(agentLine, margin, y);
    y += 5;
  }

  // Subtitle / date
  if (subtitle) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120);
    doc.text(subtitle, margin, y);
    y += 4;
  }

  // Divider
  doc.setDrawColor(220);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  return y;
}

/**
 * Draws the standard Assembl footer disclaimer on a jsPDF document.
 */
export function drawAssemblPDFFooter(
  doc: jsPDF,
  options: {
    agentName?: string;
    margin?: number;
    y?: number;
  } = {}
): void {
  const { agentName = "Assembl AI", margin = 20, y: customY } = options;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;
  let y = customY ?? 272;

  // Green accent line
  doc.setDrawColor(0, 255, 136);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 4;

  doc.setFontSize(7);
  doc.setTextColor(140);
  doc.text(
    `Generated by ${agentName} via Assembl — This is AI-generated content and should be reviewed by a qualified professional before use.`,
    margin, y, { maxWidth }
  );
  y += 4;
  doc.text(
    `© 2026 Assembl. All rights reserved. Agent designs, system prompts, and automation workflows are proprietary trade secrets of Assembl.`,
    margin, y, { maxWidth }
  );
}
