import { Download } from "lucide-react";
import jsPDF from "jspdf";

interface Message {
  role: "user" | "assistant";
  content: string;
}

interface Props {
  messages: Message[];
  agentName: string;
  agentDesignation: string;
  agentColor: string;
}

const ConversationExport = ({ messages, agentName, agentDesignation, agentColor }: Props) => {
  const handleExport = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    const addPage = () => { doc.addPage(); y = 20; };
    const checkPage = (needed: number) => { if (y + needed > 270) addPage(); };

    // Header branding
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("ASSEMBL", margin, y);
    y += 7;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120);
    doc.text(`Conversation with ${agentName} (${agentDesignation})`, margin, y);
    y += 5;
    doc.text(`Exported on ${new Date().toLocaleDateString("en-NZ", { day: "numeric", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit" })}`, margin, y);
    y += 4;
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Messages
    doc.setTextColor(0);
    for (const msg of messages) {
      checkPage(15);
      const sender = msg.role === "user" ? "You" : agentName;
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(msg.role === "user" ? 80 : 0);
      doc.text(sender, margin, y);
      y += 5;

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40);
      const plainText = msg.content
        .replace(/^#+\s*/gm, "")
        .replace(/\*\*(.*?)\*\*/g, "$1")
        .replace(/\*(.*?)\*/g, "$1")
        .replace(/^[-*]\s*\[([ xX])\]\s*/gm, (_, c) => (c.trim() ? "☑ " : "☐ "))
        .replace(/^[-*]\s+/gm, "• ");

      const lines = doc.splitTextToSize(plainText, maxWidth);
      for (const line of lines) {
        checkPage(5);
        doc.text(line, margin, y);
        y += 4.5;
      }
      y += 4;
    }

    // Footer disclaimer
    checkPage(20);
    y = Math.max(y, 260);
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 5;
    doc.setFontSize(7);
    doc.setTextColor(140);
    doc.text(
      `Generated by ${agentName} via Assembl — This is AI-generated content and should be reviewed by a qualified professional before use.`,
      margin, y, { maxWidth }
    );
    y += 5;
    doc.text(
      `© 2026 Assembl. All rights reserved. Agent designs, system prompts, and automation workflows are proprietary trade secrets of Assembl.`,
      margin, y, { maxWidth }
    );

    doc.save(`assembl-${agentName.toLowerCase()}-conversation-${new Date().toISOString().split("T")[0]}.pdf`);
  };

  if (messages.length === 0) return null;

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-1 px-2 py-1 rounded-full text-[10px] font-medium transition-colors hover:opacity-80 shrink-0"
      style={{ color: agentColor, border: `1px solid ${agentColor}20` }}
      title="Export conversation as PDF"
      aria-label="Export conversation as PDF"
    >
      <Download size={10} />
      <span className="hidden sm:inline">Export</span>
    </button>
  );
};

export default ConversationExport;
